### ISSUE TITLE
setup.py uses feedparser version 6 instead of version 5 (needs backport to the 3.12 branch)

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#123]
Hi,

it was [brought to my attention](https://bugs.gentoo.org/731840) that rss2email does not work with feedparser 6.0.0b1 (or 6.0.0b3) today. It's because of use of `feedparser.zlib.error` at https://github.com/rss2email/rss2email/blob/eb9ac58e180eb0fbbb6f49c76d8b94090b2b0680/rss2email/feed.py#L427 

For proof:
```console
# python -c 'import feedparser; print(feedparser.__version__); feedparser.zlib.error' && echo GOOD || echo BAD
5.2.1
GOOD

# python -c 'import feedparser; print(feedparser.__version__); feedparser.zlib.error' && echo GOOD || echo BAD
6.0.0b3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'feedparser' has no attribute 'zlib'
BAD
```

Are there plans to support feedparser 6?

**Comment by auouymous** [comment]
It is now `feedparser.http.zlib.error`, and `feedparser.http` didn't exist prior to 6.0. Also, 6.0.0b1 uses 5.2.1 as its version (https://github.com/kurtmckee/feedparser/blob/6.0.0b1/feedparser/__init__.py#L37).

**Comment by finkandreas** [comment]
For me the following worked with feedparser-6.0.0b3 and feedparser 5.2.1
```
        elif hasattr(_feedparser, 'zlib') and isinstance(exc, _feedparser.zlib.error):
            # <feedparser-6.0
            _LOG.error('broken compression: {}'.format(self))
            warned = True
        elif hasattr(_feedparser, 'http') and isinstance(exc, _feedparser.http.zlib.error):
            # >= feedparser-6.0
            _LOG.error('broken compression: {}'.format(self))
            warned = True
```

**Comment by Ekleog** [comment]
I don't think we'll want supporting both of those at the same time, as it's quite a bit of added complexity for little benefit. As 6.0.0b3 is probably(?) beta (I'd assume from the `b`), I'd think we should stay as is for now, and when feedparser releases 6.0.0, migrate to it

**Comment by Ekleog** [comment]
Closing this issue, as we don't want to try supporting two versions of feedparsers at once, seeing it'd be of very little benefit AFAIU :)

**Comment by hferreiro** [comment]
The pypi.org version installed with pipx and equivalents is broken because it installs feedparser 6 as its dependency.

**Comment by Ekleog** [comment]
Ugh, I just noticed that setup.py has different requirements than requirements.txt, so this is a problem that'll require backporting to a new release.

I've edited the title to better refer to the way to fix this issue, keeping upgrading feedparser to version 6 for #73. Thank you for the report! :)

**Comment by bookbound** [comment]
Fwiw, feedparser now identifies as 6.0.1. [https://github.com/kurtmckee/feedparser/blob/6.0.1/feedparser/__init__.py#L35](url)

**Comment by polm** [comment]
I believe that this is fixed by #149 but not released yet. Any plans to make a release soon?

**Comment by polm** [comment]
I believe a release with #149 was made last year and this can be closed.

**Comment by auouymous** [comment]
@polm Thank you for pointing this out.
