### ISSUE TITLE
New release with Python 3.9 support?

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#163]
Hi!

I learned today that rss2email==3.12.2 with feedparser<6 (with is 5.2.1) does not work with Python 3.9:

```console
$ r2e add name1 url2 account3
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/r2e", line 3, in <module>
    import rss2email.main
  File "/usr/lib/python3.9/site-packages/rss2email/main.py", line 34, in <module>
    from . import command as _command
  File "/usr/lib/python3.9/site-packages/rss2email/command.py", line 37, in <module>
    from . import error as _error
  File "/usr/lib/python3.9/site-packages/rss2email/error.py", line 30, in <module>
    import feedparser as _feedparser
  File "/usr/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

Hence it would rock to have a rss2email release that works with more recent feedparser>=6. Are there any plans to make a release off `master` some time soon?

Thanks and best

Sebastian

PS:
```console
$ python3.8 -c 'import base64; print(hasattr(base64, "decodestring"))'
True

$ python3.9 -c 'import base64; print(hasattr(base64, "decodestring"))'
False
```

**Comment by jpalus** [comment]
Any update on this? python 3.9 becomes more and more common so it would be great to have a new release.

**Comment by kaashif** [comment]
I agree, this seems like a fairly big deal. I'll make the change soon if no-one else does.

**Comment by Ekleog** [comment]
I've just pushed 3.12.3 out, which should solve the issue of setup.py not working since feedparser 6 went out, so that's already something.

For the update to feedparser 6 itself, which should fix this issue, we'll have to cut a release from master itself. I just went through all the open PRs to land what can be landed, as well as a couple issues to fix what was easy to fix, and will leave a few days for people to react and hopefully have some more stuff to land, as 3.13 is going to be a pretty big release (with feedparser 6).

If I forget to come back here in a few days to cut the release and/or to answer people who would have updated their PRs according to the comments, feel free to poke me!

**Comment by kaashif** [comment]
I've really not been paying attention, I didn't see that feedparser had a new version, I thought we'd have to find a way to fix this ourselves. Nice!

**Comment by amiryal** [comment]
FWIW, I have been using the master branch (and subsequently [my work-in-progress branch](https://github.com/rss2email/rss2email/compare/master...amiryal:wip), which carries all my open PRs and some others’, continually rebased on master) in my “production” setup since March 17. I haven’t yet experienced any issues related to unreleased code, especially not feedparser issues.

**Caveat 1**: I haven’t used any official release before, so I wouldn’t notice regressions on the transition to latest master.

**Caveat 2**: My setup is on Python 3.8, not 3.9, so I wouldn’t notice any further issues on Python 3.9 beyond just installing r2e.

**PS**: One issue I did have with installation was:
```
$ pipx install --spec 'git+https://github.com/rss2email/rss2email.git#egg=rss2email' rss2email
Note: Dependent package 'html2text>=2020.1.16' contains 1 binaries                  
  - html2text
No binaries associated with package rss2email. Try again with '--include-deps' to include binaries of dependent packages.
```
I don’t know if this would still be an issue upon cutting a new 3.13 release, or if it’s just an issue with the `git+https` method. At any rate, I have [a patch](https://github.com/rss2email/rss2email/commit/0499fe8313f53c1c33acf3302c39f14ab8228adc) that solves the issue for me, so you may review it for correctness and cherry-pick as necessary. (CC @ryneeverett)

**Comment by jpalus** [comment]
FWIW I've been running [patched](https://github.com/pld-linux/rss2email/commit/c19c288e432de05914649c5ab9f97d26cda6bc17) rss2email with feedparser 6 on python 3.9 for past 3 weeks and no issues so far. Still I would very much welcome new official release.

**Comment by Ekleog** [comment]
Cool, thank you for the feedback! Just, before I cut a release: @amiryal, would you mind opening a PR with https://github.com/rss2email/rss2email/commit/0499fe8313f53c1c33acf3302c39f14ab8228adc; so that CI could run on it? (I don't use poetry/pip myself, only the nix-based infrastructure, so I'm mostly relying on other people to test these issues out and the fix definitely looks legitimate)

**Comment by Ekleog** [comment]
Version 3.13.post1 is up on test-pypi, if someone not on nixos can confirm it works well for them too I'll cut the 3.13 release on real-pypi :)

**Comment by jpalus** [comment]
Tested distribution packaged 3.13.post1 (installed with setuptools) and it works fine. However there is a noticeable difference comparing to 3.12 not sure if it's expected or is it a thing of test-pypi -- previously r2e run did not produce any logs while now even debug logging is present. For me "warning" would be a good default level.

**Comment by jpalus** [comment]
...and weirdly so whole logging goes to stderr including debug and info.

**Comment by Ekleog** [comment]
Hmm that's interesting. What's the `verbose` key in your config file like? The default value when no value is provided has technically changed from `warning` to `info` with the latest release, but that's only because before that the configured log level was completely ignored… and in any case, you shouldn't be seeing debug messages. Could you also paste me an exerpt of your logs so I can try to understand what's going on?

**Comment by jpalus** [comment]
> that's only because before that the configured log level was completely ignored… 

My bad -- that's the answer. I guess years ago I've tried to debug rss2email and set `verbose=debug`. Since it had no effect it was left as is and completely forgotten. Consider adding my `Tested-by:` then and sorry for the noise :). As for logging to stderr I guess that's expected:
```
LOG.addHandler(_logging.StreamHandler())
```
https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler
> Returns a new instance of the StreamHandler class. If stream is specified, the instance will use it for logging output; otherwise, sys.stderr will be used.

**Comment by Ekleog** [comment]
Cool, thank you! Actually I'll take advantage of that to ask you a question: what do you think about the change of the default log level from warning to info ? I'm still hesitating a bit, in particular maybe in some circumstances it can mess with cron?

**Comment by Ekleog** [comment]
(also, that's definitely not noise: it was not in the changelog, so your comments will result in a fix before the release :))

**Comment by jpalus** [comment]
Even though it was an instant change to warning for me, I think move to info by default makes a lot of sense. I guess me still having `verbose = debug` in config after all those years is the best proof of this. When setting up rss2email for the first time it's quite confusing that nothing gets logged. User starts to wonder, especially on first run which may take a while, _"what is happening? did it hang?"_. Once the user likes rss2email (and note that lack of app feedback might be discouraging) and is comfortable with rss2email there is still an option to reduce logging.

**Comment by Ekleog** [comment]
Cool, thank you! I'll call it out a bit more in the changelog and release 3.13, thank you for your feedback!

**Comment by Ekleog** [comment]
Okay, 3.13 is released \o/ Closing this, now issues can come in their own new issue :)

**Comment by hartwork** [comment]
Thank you!
